### ISSUE TITLE
[Suggestion] More packages to remove.

### ISSUE THREAD

**Issue by OdinVex** [ronell1292k/OnePlus-Debloater-Script#1]
I bought a OnePlus Nord N10 5G (5G suffix is a T-Mobile (USA) branded variant indicator) that has some packages that could be removed. Their full package names are: `(OnePlus Icon Pack - Hydrogen) com.oneplus.iconpack.oneplush2`, `(OnePlus Icon Pack - Oxygen) com.oneplus.iconpack.onepluso2`, `(Canvas AOD) com.oneplus.canvasresources`, `(OnePlus Wallpaper) com.oneplus.wallpaper`.

There are a few more packages that the T-Mobile variant has which should be removed, but they require root. This bloat stuff needs to be stopped.

Considerations: `(OnePlus Weather) net.oneplus.weather` and `(OnePlus Widgets) net.oneplus.widget`

**Comment by ronellsalunke** [comment]
Added and merged
